# Generated by Django 6.0 on 2025-12-06 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['BookingDate'], 'verbose_name': 'Booking', 'verbose_name_plural': 'Booking Records'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['title'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(help_text='Date and time of the reservation'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='name',
            field=models.CharField(help_text='Name of the person making the reservation', max_length=255),
        ),
        migrations.AlterField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(help_text='Number of guests (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='inventory',
            field=models.IntegerField(help_text='Number of items available in inventory', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the item (must be greater than 0)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='title',
            field=models.CharField(help_text='Name of the menu item', max_length=255),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['BookingDate'], name='restaurant__Booking_3b579e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['name'], name='restaurant__name_417a10_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['title'], name='restaurant__title_449762_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['price'], name='restaurant__price_af720f_idx'),
        ),
    ]
